import { useEffect, useMemo, useState } from "react";
import { Building2, CheckCircle, Plus, RefreshCw, Users, X, XCircle } from "lucide-react";
import { toast } from "sonner";
import { masterDataService } from "../../services/masterData.service";
import type { Branch, ManagedUser, RecordStatus } from "../../types/masterData";

const maroon="#7A1F2B", border="#E7E7EB", muted="#6F717A";
const emptyForm={firstName:"",lastName:"",username:"",email:"",password:"",role:"BRANCH_MANAGER" as "OWNER"|"BRANCH_MANAGER",branchId:"",status:"ACTIVE" as RecordStatus};
export function AdminUsersPage(){
  const [users,setUsers]=useState<ManagedUser[]>([]),[branches,setBranches]=useState<Branch[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[open,setOpen]=useState(false),[saving,setSaving]=useState(false),[form,setForm]=useState(emptyForm);
  const load=async()=>{setLoading(true);setError("");try{const [u,b]=await Promise.all([masterDataService.users(),masterDataService.branches()]);setUsers(u);setBranches(b);}catch(e){setError(e instanceof Error?e.message:"Unable to load users");}finally{setLoading(false);}};
  useEffect(()=>{void load();},[]);
  const counts=useMemo(()=>({active:users.filter(u=>u.status==="ACTIVE").length,managers:users.filter(u=>u.role==="BRANCH_MANAGER").length}),[users]);
  const create=async()=>{setSaving(true);try{await masterDataService.createUser({...form,branchId:form.role==="OWNER"?null:form.branchId});setOpen(false);setForm(emptyForm);toast.success("User account created");await load();}catch(e){toast.error(e instanceof Error?e.message:"Unable to create user");}finally{setSaving(false);}};
  const toggle=async(user:ManagedUser)=>{try{await masterDataService.setUserStatus(user.id,user.status==="ACTIVE"?"INACTIVE":"ACTIVE");toast.success("User status updated");await load();}catch(e){toast.error(e instanceof Error?e.message:"Unable to update user");}};
  const stats=[["Total Users",users.length,Users,maroon],["Active",counts.active,CheckCircle,"#24865A"],["Inactive",users.length-counts.active,XCircle,"#999CA5"],["Branch Managers",counts.managers,Building2,"#4774C7"]] as const;
  return <div className="p-6 space-y-5">
    <div className="flex items-start justify-between"><div><h1 className="text-xl font-bold">User Management</h1><p className="text-sm mt-1" style={{color:muted}}>Manage system accounts and access roles</p></div><button onClick={()=>setOpen(true)} className="flex items-center gap-2 px-4 py-2.5 rounded-xl text-sm font-semibold text-white" style={{background:maroon}}><Plus size={15}/>Add User</button></div>
    <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-4">{stats.map(([label,value,Icon,color])=><div key={label} className="bg-white rounded-xl border p-5" style={{borderColor:border}}><div className="flex justify-between"><div><p className="text-xs font-semibold" style={{color:muted}}>{label}</p><p className="text-2xl font-bold mt-2">{value}</p></div><div className="w-9 h-9 rounded-lg flex items-center justify-center" style={{background:`${color}16`,color}}><Icon size={18}/></div></div></div>)}</div>
    <div className="bg-white rounded-xl border overflow-hidden" style={{borderColor:border}}>{loading?<div className="p-10 text-center text-sm" style={{color:muted}}>Loading users…</div>:error?<div className="p-10 text-center"><p className="text-sm text-red-600 mb-3">{error}</p><button onClick={()=>void load()} className="inline-flex gap-2 text-sm font-semibold" style={{color:maroon}}><RefreshCw size={14}/>Retry</button></div>:users.length===0?<div className="p-12 text-center text-sm" style={{color:muted}}>No user accounts found.</div>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-[#F7F8FA] text-left"><tr>{["User","Email","Role","Assigned Branch","Status","Last Login","Action"].map(h=><th className="px-4 py-3 text-xs" style={{color:muted}} key={h}>{h}</th>)}</tr></thead><tbody>{users.map(u=><tr key={u.id} className="border-t" style={{borderColor:border}}><td className="px-4 py-3 font-semibold">{u.firstName} {u.lastName}<div className="text-xs font-normal" style={{color:muted}}>@{u.username}</div></td><td className="px-4 py-3" style={{color:muted}}>{u.email}</td><td className="px-4 py-3"><span className="text-xs font-bold px-2 py-1 rounded-lg" style={{background:u.role==="OWNER"?"#F8ECEE":"#EAF0FB",color:u.role==="OWNER"?maroon:"#4774C7"}}>{u.role==="OWNER"?"Owner":"Branch Manager"}</span></td><td className="px-4 py-3" style={{color:muted}}>{u.branchName??"All Branches"}</td><td className="px-4 py-3"><span className="text-xs font-bold" style={{color:u.status==="ACTIVE"?"#24865A":"#999CA5"}}>{u.status}</span></td><td className="px-4 py-3 text-xs" style={{color:muted}}>{u.lastLoginAt?new Date(u.lastLoginAt).toLocaleString():"Never"}</td><td className="px-4 py-3"><button onClick={()=>void toggle(u)} className="px-2 py-1 rounded-lg text-xs font-bold" style={{background:u.status==="ACTIVE"?"#FDECEA":"#E8F5EF",color:u.status==="ACTIVE"?"#C13B43":"#24865A"}}>{u.status==="ACTIVE"?"Deactivate":"Activate"}</button></td></tr>)}</tbody></table></div>}</div>
    {open&&<div className="fixed inset-0 z-50 flex items-center justify-center p-4" style={{background:"rgba(0,0,0,.45)"}}><div className="bg-white rounded-2xl shadow-2xl w-full max-w-lg p-6"><div className="flex justify-between mb-5"><h2 className="font-bold text-lg">Add New User</h2><button onClick={()=>setOpen(false)}><X size={18}/></button></div><div className="grid grid-cols-2 gap-3">{(["firstName","lastName"] as const).map((key)=><label className="text-sm" key={key}>{key==="firstName"?"First Name":"Last Name"}<input value={form[key]} onChange={e=>setForm(p=>({...p,[key]:e.target.value}))} className="mt-1.5 w-full px-3 py-2.5 rounded-xl border" style={{borderColor:border}}/></label>)}</div><div className="space-y-3 mt-3"><label className="text-sm block">Username<input value={form.username} onChange={e=>setForm(p=>({...p,username:e.target.value}))} className="mt-1.5 w-full px-3 py-2.5 rounded-xl border" style={{borderColor:border}}/></label><label className="text-sm block">Email<input type="email" value={form.email} onChange={e=>setForm(p=>({...p,email:e.target.value}))} className="mt-1.5 w-full px-3 py-2.5 rounded-xl border" style={{borderColor:border}}/></label><label className="text-sm block">Temporary Password<input type="password" value={form.password} onChange={e=>setForm(p=>({...p,password:e.target.value}))} className="mt-1.5 w-full px-3 py-2.5 rounded-xl border" style={{borderColor:border}} placeholder="At least 10 characters"/></label><label className="text-sm block">Role<select value={form.role} onChange={e=>setForm(p=>({...p,role:e.target.value as typeof p.role,branchId:""}))} className="mt-1.5 w-full px-3 py-2.5 rounded-xl border" style={{borderColor:border}}><option value="BRANCH_MANAGER">Branch Manager</option><option value="OWNER">Owner</option></select></label>{form.role==="BRANCH_MANAGER"&&<label className="text-sm block">Assigned Branch<select value={form.branchId} onChange={e=>setForm(p=>({...p,branchId:e.target.value}))} className="mt-1.5 w-full px-3 py-2.5 rounded-xl border" style={{borderColor:border}}><option value="">Select branch…</option>{branches.map(b=><option value={b.id} key={b.id}>{b.name}</option>)}</select></label>}</div><div className="flex gap-3 mt-6"><button onClick={()=>setOpen(false)} className="flex-1 py-2.5 rounded-xl border" style={{borderColor:border}}>Cancel</button><button disabled={saving} onClick={()=>void create()} className="flex-1 py-2.5 rounded-xl text-white font-semibold" style={{background:maroon}}>{saving?"Creating…":"Create User"}</button></div></div></div>}
  </div>;
}
