import { useEffect, useState } from "react";
import { Building2, CheckCircle, Plus, RefreshCw, X } from "lucide-react";
import { toast } from "sonner";
import { masterDataService } from "../../services/masterData.service";
import type { Branch, RecordStatus } from "../../types/masterData";
const maroon="#7A1F2B",border="#E7E7EB",muted="#6F717A";
const empty={code:"",name:"",location:"",status:"ACTIVE" as RecordStatus};
export function AdminBranchesPage(){
  const [branches,setBranches]=useState<Branch[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[open,setOpen]=useState(false),[saving,setSaving]=useState(false),[form,setForm]=useState(empty);
  const load=async()=>{setLoading(true);setError("");try{setBranches(await masterDataService.branches());}catch(e){setError(e instanceof Error?e.message:"Unable to load branches");}finally{setLoading(false);}}; useEffect(()=>{void load();},[]);
  const create=async()=>{setSaving(true);try{await masterDataService.createBranch(form);setOpen(false);setForm(empty);toast.success("Branch created");await load();}catch(e){toast.error(e instanceof Error?e.message:"Unable to create branch");}finally{setSaving(false);}};
  return <div className="p-6 space-y-5"><div className="flex items-start justify-between"><div><h1 className="text-xl font-bold">Branch Management</h1><p className="text-sm mt-1" style={{color:muted}}>Manage Libro Espresso branch configurations and assignments</p></div><button onClick={()=>setOpen(true)} className="flex items-center gap-2 px-4 py-2.5 rounded-xl text-sm font-semibold text-white" style={{background:maroon}}><Plus size={15}/>Add Branch</button></div>
  <div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><div className="bg-white rounded-xl border p-5" style={{borderColor:border}}><div className="flex justify-between"><div><p className="text-xs font-semibold" style={{color:muted}}>Total Branches</p><p className="text-2xl font-bold mt-2">{branches.length}</p></div><Building2 color={maroon}/></div></div><div className="bg-white rounded-xl border p-5" style={{borderColor:border}}><div className="flex justify-between"><div><p className="text-xs font-semibold" style={{color:muted}}>Active Branches</p><p className="text-2xl font-bold mt-2">{branches.filter(b=>b.status==="ACTIVE").length} of {branches.length}</p></div><CheckCircle color="#24865A"/></div></div></div>
  <div className="bg-white rounded-xl border overflow-hidden" style={{borderColor:border}}>{loading?<div className="p-10 text-center text-sm" style={{color:muted}}>Loading branches…</div>:error?<div className="p-10 text-center"><p className="text-sm text-red-600 mb-3">{error}</p><button onClick={()=>void load()} className="inline-flex gap-2 text-sm font-semibold" style={{color:maroon}}><RefreshCw size={14}/>Retry</button></div>:branches.length===0?<div className="p-12 text-center" style={{color:muted}}>No branches found.</div>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-[#F7F8FA] text-left"><tr>{["Code","Branch Name","Location","Manager","Status","Last Updated"].map(h=><th key={h} className="px-4 py-3 text-xs" style={{color:muted}}>{h}</th>)}</tr></thead><tbody>{branches.map(b=><tr key={b.id} className="border-t" style={{borderColor:border}}><td className="px-4 py-3 font-mono text-xs" style={{color:muted}}>{b.code}</td><td className="px-4 py-3 font-semibold">{b.name}</td><td className="px-4 py-3" style={{color:muted}}>{b.location}</td><td className="px-4 py-3" style={{color:muted}}>{b.manager??"Unassigned"}</td><td className="px-4 py-3"><span className="text-xs font-bold" style={{color:b.status==="ACTIVE"?"#24865A":"#999CA5"}}>{b.status}</span></td><td className="px-4 py-3 text-xs" style={{color:muted}}>{new Date(b.updatedAt).toLocaleString()}</td></tr>)}</tbody></table></div>}</div>
  {open&&<div className="fixed inset-0 z-50 flex items-center justify-center p-4" style={{background:"rgba(0,0,0,.45)"}}><div className="bg-white rounded-2xl shadow-2xl w-full max-w-md p-6"><div className="flex justify-between mb-5"><h2 className="font-bold text-lg">Add Branch</h2><button onClick={()=>setOpen(false)}><X size={18}/></button></div><div className="space-y-4">{(["code","name","location"] as const).map(key=><label key={key} className="text-sm block">{key==="code"?"Branch Code":key==="name"?"Branch Name":"Location"}<input value={form[key]} onChange={e=>setForm(p=>({...p,[key]:e.target.value}))} className="mt-1.5 w-full px-3 py-2.5 rounded-xl border" style={{borderColor:border}}/></label>)}<label className="text-sm block">Status<select value={form.status} onChange={e=>setForm(p=>({...p,status:e.target.value as RecordStatus}))} className="mt-1.5 w-full px-3 py-2.5 rounded-xl border" style={{borderColor:border}}><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option></select></label></div><div className="flex gap-3 mt-6"><button onClick={()=>setOpen(false)} className="flex-1 py-2.5 rounded-xl border" style={{borderColor:border}}>Cancel</button><button disabled={saving} onClick={()=>void create()} className="flex-1 py-2.5 rounded-xl text-white font-semibold" style={{background:maroon}}>{saving?"Creating…":"Create Branch"}</button></div></div></div>}
  </div>;
}
