import type { UserRole } from "./auth";
export type RecordStatus = "ACTIVE" | "INACTIVE";
export interface Branch { id:string; code:string; name:string; location:string; status:RecordStatus; manager?:string|null; managerId?:string|null; managerStatus?:RecordStatus|null; createdAt:string; updatedAt:string; lastActivityAt:string; lastActivityDescription:string }
export interface ManagedUser { id:string; branchId:string|null; firstName:string; lastName:string; email:string; username:string; phoneNumber:string|null; position:string; role:UserRole; status:RecordStatus; branchCode:string|null; branchName:string|null; lastLoginAt:string|null; createdAt:string; updatedAt:string; lastActivityAt:string; lastActivityDescription:string }
export interface InventoryItem { id:string; sku:string; name:string; category:string; unit:string; unitCost:number; reorderLevel:number; status:RecordStatus; itemScope:"GLOBAL"|"BRANCH";originBranchId:string|null;originBranchName?:string|null }
export interface MenuItem { id:string; code:string; name:string; category:string; sellingPrice:number; status:RecordStatus }
export interface MenuCategory { id:string; name:string; description:string; status:RecordStatus; createdAt:string; updatedAt:string }
export interface MenuProductIngredient { id:string; inventoryItemId:string; sku:string; name:string; quantity:number; unit:string; inventoryUnit:string; unitCost:number; ingredientCost:number }
export interface RecipeVersionSummary { id:string; version:number; effectiveFrom:string; effectiveTo:string|null; yieldQuantity:number; status:RecordStatus; changeReason:string|null; createdByName:string|null; createdAt:string }
export type ProductScope = "GLOBAL" | "BRANCH";
export type ProductApprovalStatus = "PENDING_OWNER" | "APPROVED" | "REJECTED";
export type BranchProductStatus = "PENDING_OWNER" | "PENDING_MANAGER" | "APPROVED" | "REJECTED";
export interface BranchProductApproval { branchId:string; branchName:string; status:BranchProductStatus; isActive:boolean; reviewComment:string|null; reviewedAt:string|null }
export interface MenuProduct { id:string; code:string; name:string; category:string; categoryId:string|null; description:string; sellingPrice:number; status:RecordStatus; productScope:ProductScope; originBranchId:string|null; originBranchName:string|null; approvalStatus:ProductApprovalStatus; ownerReviewComment:string|null; branchAvailabilityStatus:BranchProductStatus|null; branchMenuStatus:RecordStatus|null; branchApprovals:BranchProductApproval[]; createdByName:string|null; recipeId:string|null; recipeName:string|null; recipeVersion:number|null; recipeEffectiveFrom:string|null; recipeEffectiveTo:string|null; recipeChangeReason:string|null; recipeHasHistoricalSales:boolean; recipeHistory:RecipeVersionSummary[]; yieldQuantity:number|null; recipeCost:number; marginAmount:number; marginRate:number; ingredients:MenuProductIngredient[]; createdAt:string; updatedAt:string }
export interface RecipeIngredient { id:string; inventoryItemId:string; sku:string; name:string; quantity:number; unit:string; inventoryUnit:string; unitCost:number }
export interface Recipe { id:string; menuItemId:string; name:string; yieldQuantity:number; status:RecordStatus; version:number; effectiveFrom:string; effectiveTo:string|null; changeReason:string|null; createdByName:string|null; menuItem:MenuItem; items:RecipeIngredient[] }
