import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it } from "vitest";
import { ShrinkageAiAnalysisPanel } from "./ShrinkagePage";

describe("AI-Assisted Shrinkage Analysis presentation", () => {
  it("labels a validated Gemini response and renders each advisory section", () => {
    const markup = renderToStaticMarkup(React.createElement(ShrinkageAiAnalysisPanel, {
      loading: false,
      result: {
        source: "GOOGLE_GEMINI",
        analysis: {
          observation: "A shortage was recorded.",
          risk: "The cause is not established.",
          recommendation: "Review the count and supporting records.",
          limitations: "Evidence is limited.",
        },
      },
    }));
    expect(markup).toContain("AI-Assisted Shrinkage Analysis");
    expect(markup).toContain("Generated by Gemini from calculated shrinkage findings");
    expect(markup).toContain("Observation");
    expect(markup).toContain("Risk / Pattern");
    expect(markup).toContain("Recommendation");
    expect(markup).toContain("Confidence / Limitation");
  });

  it("shows a non-AI unavailable state without claiming Gemini generated it", () => {
    const markup = renderToStaticMarkup(React.createElement(ShrinkageAiAnalysisPanel, {
      loading: false,
      result: { source: "UNAVAILABLE", analysis: null },
    }));
    expect(markup).toContain("AI-assisted analysis is currently unavailable.");
    expect(markup).not.toContain("Generated by Gemini");
  });
});
