import { describe, expect, it } from "vitest";
import type { PredictiveForecast } from "../../types/predictive";
import { predictiveDataSufficiency, predictiveInsightSourceLabel } from "./PredictiveAnalyticsPage";

const forecastContext = (
  observedSalesDays: number,
  confidence: PredictiveForecast["methodology"]["confidence"],
  mae: number | null,
  evaluatedDays: number,
  branchName = "Gulod / Main Branch",
) => ({
  scope: { branchId: "branch-1", branchName, forecastStart: "2026-10-02", forecastEnd: "2026-10-31" },
  methodology: {
    historicalStart: "2025-10-02", historicalEnd: "2026-10-01", observedSalesDays, confidence,
    insightSource: "SYSTEM_ANALYSIS" as const, disclaimer: "", salesMaeMethod: "", ingredientMaeMethod: "", stockProjectionAssumption: "",
  },
  accuracy: {
    sales: {
      overall: {
        evaluationStart: evaluatedDays ? "2026-09-01" : null,
        evaluationEnd: evaluatedDays ? "2026-09-30" : null,
        evaluatedDays, observations: [], mae, averageActual: null, averageForecast: null,
        insufficientHistory: evaluatedDays < 30,
      },
      branches: [],
    },
    ingredients: [],
  },
});

describe("Predictive Analytics insight source", () => {
  it("labels validated Gemini narratives distinctly", () => {
    expect(predictiveInsightSourceLabel("GOOGLE_GEMINI")).toBe("Generated by Gemini from calculated findings");
  });

  it("labels deterministic fallback insights without implying Gemini generated them", () => {
    expect(predictiveInsightSourceLabel("SYSTEM_ANALYSIS")).toBe("Generated from calculated system findings");
  });
});

describe("Predictive Analytics data sufficiency messaging", () => {
  it("explains LOW confidence when only one sales observation exists", () => {
    const result = predictiveDataSufficiency(forecastContext(1, "LOW", null, 0));
    expect(result.lowHistoryMessage).toBe("Low confidence — only 1 recorded sales day is available. Historical data is insufficient to validate forecast accuracy.");
  });

  it("explains why MAE is unavailable", () => {
    expect(predictiveDataSufficiency(forecastContext(1, "LOW", null, 0)).maeMessage)
      .toBe("MAE unavailable — insufficient historical data for backtesting.");
  });

  it("explains zero evaluated days", () => {
    expect(predictiveDataSufficiency(forecastContext(1, "LOW", null, 0)).evaluatedDaysMessage)
      .toBe("No historical forecasts could be evaluated yet.");
  });

  it("hides the notice when adequate evaluated history exists", () => {
    const result = predictiveDataSufficiency(forecastContext(90, "HIGH", 125, 30));
    expect(result).toMatchObject({ showNotice: false, lowHistoryMessage: null, maeMessage: null, evaluatedDaysMessage: null });
  });

  it("retains the API-provided branch scope in the notice", () => {
    expect(predictiveDataSufficiency(forecastContext(1, "LOW", null, 0, "Gulod / Main Branch")).scope)
      .toBe("Gulod / Main Branch");
  });
});
